---
# Description of the types of training available in the database
- types:
  - name: Scenario-Based Training
    category: scenarios
  - name: Topic-Based Training [N/A]
    category: topics

# Description of the scenarios available in the training database
- scenarios:

  # Content inspired by the U.S. NIST "Technical Guide to Information
  # Security Testing and Assessment"
  - name: Information Security Testing and Assessment
    levels:
      - name: Level 1
        content: NIST-level1-content-en.yml
        range: NIST-level1-range.yml
      - name: Level 2 [N/A]
